name: Update Hugging Face Space

on:
	push:
		branches:
			- main
	workflow_dispatch:

jobs:
	deploy:
		runs-on: ubuntu-latest
		steps:
			- name: Checkout
				uses: actions/checkout@v4

			- name: Push to Hugging Face
				env:
					HF_TOKEN: ${{ secrets.HF_TOKEN }}
				run: |
					git config --global user.name "github-actions[bot]"
					git config --global user.email "github-actions[bot]@users.noreply.github.com"
					git remote add hf https://chintu4:${HF_TOKEN}@huggingface.co/spaces/chintu4/med-bot
					git push --force hf HEAD:main
